### ISSUE TITLE
Publish forthcoming and past workshops on the web

### ISSUE THREAD

**Issue by jezcope** [LibraryCarpentry/librarycarpentry.github.io#26]
Ideally, the list of workshops should be:

1. Rendered on the website; and
2. Downloadable in machine-readable form e.g. JSON

@weaverbel Not sure if we need to do this ourselves or just tap into AMY?

**Comment by weaverbel** [comment]
Let's discuss it when we have a more fleshed out proposal @jezcope?I have AMY access but it is a bottleneck to have only one person with those credentials, and anyway, we want something open. I will check whether I can export LC workshops info from AMY.

**Comment by jezcope** [comment]
Ok, I've drafted up a workshops page here, which you can view at https://jezcope.github.io/librarycarpentry-website/workshops/

I've imported the data from the Google sheet into this YAML file, roughly following the structure of the data that AMY outputs: https://github.com/jezcope/librarycarpentry-website/blob/master/_data/fake_amy.yml

The whole thing needs refinement and the process documenting, and the data definitely needs improving, but we're getting there.

**Comment by drjwbaker** [comment]
We certainly are getting there. Great job Jez. We will need some documentation for adding new data. Feel free to hand that over if you run out of time.

**Comment by drjwbaker** [comment]
@jezcope: are you happy to leave issue here or would rather consolidate at https://github.com/data-lessons/librarycarpentry/issues?

**Comment by jezcope** [comment]
@drjwbaker @weaverbel Ok, I've pushed an update with the workshop info held in a more maintainable way. Data about workshops is now in [`_data/fake_amy.yaml`](https://github.com/LibraryCarpentry/librarycarpentry.github.io/blob/master/_data/fake_amy.yml) (name chosen because the format mirrors that exported by [AMY](https://github.com/swcarpentry/amy) for the SWC website, but probably shouldn't really be that). There's a line down near the bottom like this:

```yaml
- &id_ws_future # future workshops: move this line down as time passes
```

which separates the past and future workshops — this needs to be moved further down each time a workshop goes past. New workshops can be added by copying and pasting an existing workshop entry. They look like this:

```yaml
  - address: Information Commons, University of Sheffield, Sheffield
    contact: j.s.cope@sheffield.ac.uk
    country: gb
    start: 2017-03-07
    end: 2017-03-23
    eventbrite_id: ''
    humandate: 7 & 23 Jun 2017
    latitude:  41.7901128
    longitude: -87.6007318
    slug: 2017-03-07-sheffield-lc
    tags:
    - {name: LC}
    url: https://jezcope.github.io/2017-03-07-sheffield-lc/
    venue: University of Sheffield
    who: "Jez Cope, Martin Callaghan, Elly Cope"
    numbers: 50
    what: "Data Intro, Spreadsheets (from DC), OpenRefine, Python"
    notes: null
    blogs: null
```

The key fields that are currently being used are: `url`, `venue` and `humandate`, but try to fill in as many of the others as possible for future use.

This still needs better documentation, of course!
